networks:
  kitchenwatch_net:
    driver: bridge

volumes:
  grafana-data:

services:
  edge:
    build:
      context: .
      dockerfile: docker/edge.Dockerfile
    container_name: kitchenwatch-edge-dev
    working_dir: /workspace/kitchenwatch
    depends_on:
      - tempo
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthz" ]
      interval: 3s
      timeout: 2s
      retries: 10
    environment:
      - LOG_LEVEL=INFO
      - LOG_JSON=false
    ports:
      - "8080:8080"
    volumes:
      - ./src:/workspace/kitchenwatch/src
      - ./data:/workspace/kitchenwatch/data
    restart: unless-stopped
    networks:
      - kitchenwatch_net


  simulator:
    build:
      context: .
      dockerfile: docker/simulator.Dockerfile
    container_name: kitchenwatch-simulator-dev
    working_dir: /workspace/kitchenwatch
    depends_on:
      edge:
        condition: service_healthy
    command:  []
    environment:
      - PYTHONUNBUFFERED=1
      - UV_ENV=dev
      - FUSED_DIR=/workspace/kitchenwatch/data/fused
      - LOG_LEVEL=INFO
      - LOG_JSON=false
    volumes:
      # Mount local folders for live development (overrides COPY in Dockerfile)
      - ./src:/workspace/kitchenwatch/src
      - ./demo:/workspace/kitchenwatch/demo
      - ./data:/workspace/kitchenwatch/data
      - ./scripts:/workspace/kitchenwatch/scripts
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - kitchenwatch_net

  prometheus:
    image: prom/prometheus:latest
    container_name: kitchenwatch-prometheus
    volumes:
      - ./docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kitchenwatch_net

  grafana:
    image: grafana/grafana:latest
    container_name: kitchenwatch-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana_datasources.yaml:/etc/grafana/provisioning/datasources/cortexguard.yaml:ro
      - ./docker/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/cortexguard-dashboards.yaml:ro
      - ./docker/grafana_dashboard.json:/var/lib/grafana/dashboards/cortexguard-edge.json:ro
      - grafana-data:/var/lib/grafana
    networks:
      - kitchenwatch_net

  tempo:
    image: grafana/tempo:latest
    container_name: kitchenwatch-tempo
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml:ro
      - ./docker/tempo-data:/var/tempo
    command: ["--config.file=/etc/tempo.yaml"]
    ports:
      - "4318:4318"
      - "3100:3100"
    networks:
      - kitchenwatch_net
