from typing import Any

from pydantic import BaseModel, Field


class AgentToolCall(BaseModel):
    """
    Represents a single atomic command or function call generated by the LLM.
    This model captures the LLM's decision (what to run) and the validated parameters (how to run it).
    """

    # 1. The Action (The Verb/Function Name)
    action_name: str = Field(
        ...,
        description="The name of the capability being invoked (e.g., 'GRILL_ITEM', 'RESET_DEVICE').",
    )

    # 2. The Parameters (The Arguments, including the Tool ID)
    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="A dictionary of validated parameters for the function. Must include the 'tool_id' if required by the function's schema.",
    )
