from __future__ import annotations

import uuid
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

from .agent_tool_call import AgentToolCall
from .goal import GoalContext


class PlanSource(str, Enum):
    EDGE_POLICY = "edge_policy"  # from RemediationPolicy
    CLOUD_AGENT = "cloud_agent"  # from GCP planner
    USER_INTENT = "user_intent"  # recipe plans


class PlanType(str, Enum):
    """The type of plan, indicating its source or purpose."""

    RECIPE = "recipe"
    REMEDIATION = "remediation"


class StepStatus(str, Enum):
    """Execution status of a single step within a plan."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class PlanStatus(str, Enum):
    """Overall execution status of the entire plan."""

    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"
    PREEMPTED = "preempted"
    CANCELLED = "cancelled"


class PlanStep(BaseModel):
    """
    A single step in a plan, managing execution state and linking to the LLM's cognition
    (only when complex reasoning is involved).
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this specific step.",
    )

    description: str = Field(
        description="A natural language explanation of what this step achieves."
    )

    # --- COMMAND AND OPTIONAL REASONING LINK ---

    action: AgentToolCall = Field(
        description="The atomic command (function name + parameters) to perform in this step."
    )

    # This is the key change: Making the trace ID Optional
    trace_id: str | None = Field(
        default=None,
        description="Optional ID linking this step to the specific ReasoningTrace that generated it. Omitted for routine steps.",
    )

    # --- EXECUTION STATE ---

    status: StepStatus = Field(
        default=StepStatus.PENDING, description="The current execution status of this step."
    )

    started_at: datetime | None = Field(
        default=None, description="Timestamp when execution started."
    )

    completed_at: datetime | None = Field(
        default=None, description="Timestamp when execution completed."
    )

    attempts: int = Field(
        default=0, description="The number of times this step has been attempted."
    )


class Plan(BaseModel):
    """
    The complete, ordered sequence of steps generated by the planning agent
    to fulfill the user's intent (the Blueprint).
    """

    plan_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this plan instance.",
    )
    context: GoalContext = Field(description="The original intent and goal this plan addresses.")
    plan_type: PlanType = Field(description="The type of plan (e.g., RECIPE or REMEDIATION).")
    steps: list[PlanStep] = Field(description="The ordered list of steps to execute.")
    status: PlanStatus = Field(
        default=PlanStatus.PENDING, description="The overall execution status of the plan."
    )

    # provenance
    source: PlanSource = Field(default=PlanSource.USER_INTENT)
    trace_id: str | None = Field(default=None)  # ties back to Mayday/escalation or reasoning

    # Optional fields for tracking execution
    created_at: datetime = Field(default_factory=datetime.now)
    started_at: datetime | None = None
    completed_at: datetime | None = None

    def __repr__(self) -> str:
        return (
            f"Plan(id='{self.plan_id[:8]}...', type={self.plan_type.name}, "
            f"status={self.status.name}, steps={len(self.steps)})"
        )
