import uuid
from datetime import datetime

from pydantic import BaseModel, Field

from cortexguard.edge.models.anomaly_event import AnomalyEvent
from cortexguard.edge.models.goal import GoalContext
from cortexguard.edge.models.plan import Plan, PlanSource, PlanStep, PlanType


class RemediationPolicy(BaseModel):
    """
    A short, corrective plan generated by the Local Policy Agent in response to an anomaly.

    This replaces the current plan execution and aims to return the system to a safe,
    stable, and recoverable state (e.g., retreat, retry, cool down).
    """

    policy_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique ID for this policy execution.",
    )

    # Context: What caused this policy?
    trigger_event: AnomalyEvent = Field(
        ..., description="The full AnomalyEvent object that caused the trigger."
    )

    # The Brain: Why did the agent choose this?
    reasoning_trace: str = Field(
        ...,
        description="Detailed, human-readable reasoning (Chain-of-Thought) explaining the policy decision.",
    )

    risk_assessment: str = Field(
        ...,
        description="Qualitative assessment of the risk associated with executing this policy (e.g. 'LOW - Passive Wait').",
    )

    # The Output: What to do
    corrective_steps: list[PlanStep] = Field(
        ..., description="A sequence of 1-5 PlanSteps to execute for remediation."
    )

    escalation_required: bool = Field(
        default=False,
        description="If True, this policy is just a placeholder for 'Stop and ask Cloud'.",
    )

    created_at: datetime = Field(default_factory=datetime.now)

    def to_plan_steps(self) -> list[PlanStep]:
        """Convenience method to retrieve the steps ready for injection into the executor queue."""
        return self.corrective_steps

    def to_plan(
        self,
        goal: GoalContext,
        trace_id: str | None = None,
        created_at: datetime | None = None,
    ) -> Plan:
        created_at = created_at or datetime.now()
        return Plan(
            context=goal,
            plan_type=PlanType.REMEDIATION,
            steps=self.to_plan_steps(),
            source=PlanSource.EDGE_POLICY,
            trace_id=trace_id or self.policy_id,
            created_at=created_at,
        )
