from __future__ import annotations

import uuid
from datetime import UTC, datetime
from typing import Any

import pytest

from cortexguard.cloud.graph.workflow import build_graph, run_planning_workflow
from cortexguard.cloud.persistence.models import IncidentRecord
from cortexguard.cloud.persistence.repository import InMemoryIncidentRepository
from cortexguard.cloud.planner.llm_client import PlannerResponse
from cortexguard.cloud.planner.mock_client import MockLLMClient
from cortexguard.cloud.validation.capability_adapter import CapabilityAdapter
from cortexguard.cloud.validation.plan_validator import PlanValidator
from cortexguard.edge.models.agent_tool_call import AgentToolCall
from cortexguard.edge.models.goal import GoalContext
from cortexguard.edge.models.mayday_packet import MaydayPacket, SystemHealth
from cortexguard.edge.models.plan import Plan, PlanSource, PlanStep, PlanType


def _make_packet() -> MaydayPacket:
    return MaydayPacket(
        trace_id="trace-001",
        device_id="robot-01",
        timestamp=datetime.now(UTC),
        health=SystemHealth(),
    )


def _canned_plan() -> Plan:
    return Plan(
        plan_id=str(uuid.uuid4()),
        context=GoalContext(
            goal_id=str(uuid.uuid4()),
            user_prompt="Cloud planner safe park",
            intent="Park arm safely pending operator review",
        ),
        plan_type=PlanType.REMEDIATION,
        source=PlanSource.CLOUD_AGENT,
        steps=[
            PlanStep(
                description="Park arm in safe home position",
                action=AgentToolCall(
                    action_name="PLACE_ITEM",
                    arguments={
                        "item_name": "arm",
                        "target_location": "home",
                        "tool_id": "RoboticGripper_A",
                    },
                ),
            )
        ],
    )


def _make_llm(needs_human_review: bool = False) -> MockLLMClient:
    return MockLLMClient(
        fixed_response=PlannerResponse(
            candidate_plan=_canned_plan(),
            confidence=0.9,
            needs_human_review=needs_human_review,
            rationale="Generated by mock for test",
            raw_provider_metadata={},
        )
    )


@pytest.mark.asyncio
async def test_run_planning_workflow_returns_incident_id() -> None:
    repo = InMemoryIncidentRepository()
    graph = build_graph(repo, None, None, None)
    final_state = await run_planning_workflow(_make_packet(), graph)
    assert final_state["incident_id"] is not None


@pytest.mark.asyncio
async def test_run_planning_workflow_decision_is_valid() -> None:
    repo = InMemoryIncidentRepository()
    graph = build_graph(repo, None, None, None)
    final_state = await run_planning_workflow(_make_packet(), graph)
    assert final_state["decision"] in {"plan_ready", "needs_human", "no_safe_plan", None}


@pytest.mark.asyncio
async def test_run_planning_workflow_errors_is_list() -> None:
    repo = InMemoryIncidentRepository()
    graph = build_graph(repo, None, None, None)
    final_state = await run_planning_workflow(_make_packet(), graph)
    assert isinstance(final_state["errors"], list)


class _BrokenRetrievalStore:
    async def retrieve_similar(
        self, packet: MaydayPacket, top_k: int = 5
    ) -> list[tuple[str, float, IncidentRecord | None]]:
        raise RuntimeError("store unavailable")


@pytest.mark.asyncio
async def test_node_exception_results_in_needs_human() -> None:
    repo = InMemoryIncidentRepository()
    broken_store = _BrokenRetrievalStore()
    graph = build_graph(repo, broken_store, None, None)
    final_state = await run_planning_workflow(_make_packet(), graph)
    assert final_state["decision"] == "needs_human"
    assert len(final_state["errors"]) > 0


# ---------------------------------------------------------------------------
# Interrupt / resume tests (checkpointer required)
# ---------------------------------------------------------------------------
# These tests exercise the actual interrupt() path in route_decision by
# providing a mock LLM that returns needs_human_review=True, which causes
# PlanValidator to return passed=False (llm requested human review).
# The graph then enters the needs_human branch and calls interrupt().


@pytest.mark.asyncio
async def test_graph_interrupts_and_resumes_with_approval() -> None:
    """Graph pauses at needs_human and resumes to plan_ready on operator approval."""
    repo = InMemoryIncidentRepository()
    llm = _make_llm(needs_human_review=True)
    validator = PlanValidator(CapabilityAdapter.load_default())
    graph = build_graph(repo, None, llm, validator, checkpoint_store="memory")
    packet = _make_packet()
    config = {"configurable": {"thread_id": packet.trace_id}}

    await run_planning_workflow(packet, graph, thread_id=packet.trace_id)

    snap = graph.get_state(config)
    next_tasks = snap.next
    assert bool(next_tasks), "Graph should have interrupted at route_decision"

    resume_input: dict[str, Any] = {
        "operator_response": {"approved": True, "outcome": "resolved"},
    }
    final_state = await graph.ainvoke(resume_input, config)

    snap2 = graph.get_state(config)
    assert not snap2.next
    assert final_state.get("decision") == "plan_ready"


@pytest.mark.asyncio
async def test_graph_interrupts_and_resumes_with_timeout() -> None:
    """Resume with operator_response=timeout yields no_safe_plan."""
    repo = InMemoryIncidentRepository()
    llm = _make_llm(needs_human_review=True)
    validator = PlanValidator(CapabilityAdapter.load_default())
    graph = build_graph(repo, None, llm, validator, checkpoint_store="memory")
    packet = _make_packet()
    config = {"configurable": {"thread_id": packet.trace_id}}

    await run_planning_workflow(packet, graph, thread_id=packet.trace_id)

    snap = graph.get_state(config)
    assert snap.next

    resume_input: dict[str, Any] = {
        "operator_response": {"timeout": True},
    }
    final_state = await graph.ainvoke(resume_input, config)

    snap2 = graph.get_state(config)
    assert not snap2.next
    assert final_state.get("decision") == "no_safe_plan"


@pytest.mark.asyncio
async def test_graph_interrupts_and_resumes_with_rejection() -> None:
    """Resume with operator_response=reject yields no_safe_plan."""
    repo = InMemoryIncidentRepository()
    llm = _make_llm(needs_human_review=True)
    validator = PlanValidator(CapabilityAdapter.load_default())
    graph = build_graph(repo, None, llm, validator, checkpoint_store="memory")
    packet = _make_packet()
    config = {"configurable": {"thread_id": packet.trace_id}}

    await run_planning_workflow(packet, graph, thread_id=packet.trace_id)

    snap = graph.get_state(config)
    assert snap.next

    resume_input: dict[str, Any] = {
        "operator_response": {"action": "reject"},
    }
    final_state = await graph.ainvoke(resume_input, config)

    snap2 = graph.get_state(config)
    assert not snap2.next
    assert final_state.get("decision") == "no_safe_plan"


@pytest.mark.asyncio
async def test_graph_no_interrupt_when_no_human_review_needed() -> None:
    """When needs_human_review=False, the graph runs to completion without interrupting."""
    repo = InMemoryIncidentRepository()
    llm = _make_llm(needs_human_review=False)
    validator = PlanValidator(CapabilityAdapter.load_default())
    graph = build_graph(repo, None, llm, validator, checkpoint_store="memory")
    packet = _make_packet()
    config = {"configurable": {"thread_id": packet.trace_id}}

    final_state = await run_planning_workflow(packet, graph, thread_id=packet.trace_id)

    snap = graph.get_state(config)
    assert not snap.next
    assert final_state.get("decision") == "plan_ready"


@pytest.mark.asyncio
async def test_graph_resume_with_plan_override() -> None:
    """Operator can override the plan on resume."""
    repo = InMemoryIncidentRepository()
    llm = _make_llm(needs_human_review=True)
    validator = PlanValidator(CapabilityAdapter.load_default())
    graph = build_graph(repo, None, llm, validator, checkpoint_store="memory")
    packet = _make_packet()
    config = {"configurable": {"thread_id": packet.trace_id}}

    await run_planning_workflow(packet, graph, thread_id=packet.trace_id)

    snap = graph.get_state(config)
    assert snap.next

    override_plan = _canned_plan()
    resume_input: dict[str, Any] = {
        "operator_response": {
            "approved": True,
            "plan_override": override_plan,
            "outcome": "resolved",
        },
    }
    final_state = await graph.ainvoke(resume_input, config)

    assert final_state.get("decision") == "plan_ready"
    # The overridden plan should be set
    overridden = final_state.get("candidate_plan")
    assert overridden is not None
    assert overridden.plan_id == override_plan.plan_id
