# ---- Base Python image ----
FROM python:3.12-slim AS base

# Environment setup
ENV PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    VENV_PATH=/opt/venvs/kitchenwatch \
    UV_ENV=dev \
    UV_VENV_PATH=/opt/venvs/kitchenwatch \
    PATH="/opt/venvs/kitchenwatch/bin:$PATH"

# Working directory
WORKDIR /workspace/kitchenwatch


# ---- Shell utilities and Taskfile support ----
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    coreutils bash-completion ca-certificates \
    git curl wget build-essential make && \
    curl -sL https://taskfile.dev/install.sh | sh && \
    mv ./bin/task /usr/local/bin/task && \
    rm -rf /var/lib/apt/lists/*


# ---- Create virtual environment and install uv ----
RUN python -m venv $VENV_PATH && \
    $VENV_PATH/bin/pip install --upgrade pip && \
    $VENV_PATH/bin/pip install "uv>=0.9.5"

# ---- Dependency metadata ----
COPY pyproject.toml uv.lock ./

# ---- Create non-root user ----
RUN useradd -ms /bin/bash vscode && \
    chown -R vscode:vscode /workspace

# ---- Install dependencies ----
RUN $VENV_PATH/bin/python -m uv sync --group dev --frozen --active && \
    chown -R vscode:vscode $VENV_PATH


USER vscode
CMD ["/bin/bash"]

# ---- Activate environment----
RUN echo 'source /opt/venvs/kitchenwatch/bin/activate' >> /home/vscode/.bashrc
