import uuid
from datetime import datetime
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field


class ActionStatus(str, Enum):
    """Execution status of a dynamic action command."""

    PENDING = "PENDING"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class Action(BaseModel):
    """
    A dynamic command generated by the Orchestrator to interact with a specific Tool.
    It includes tracking and status fields necessary for execution monitoring.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this specific action instance.",
    )
    # The actual command payload fields
    tool_id: str = Field(description="The ID of the targeted Tool (from tool.py).")
    capability: str = Field(description="The name of the function to execute (e.g., 'SET_TEMP').")
    arguments: dict[str, Any] = Field(
        default_factory=dict, description="Dynamic key-value arguments required by the capability."
    )

    # Runtime/Tracking fields
    created_at: datetime = Field(
        default_factory=datetime.now, description="Timestamp when the action was created."
    )
    status: ActionStatus = Field(
        default=ActionStatus.PENDING, description="Current execution status of the action."
    )

    def __repr__(self) -> str:
        return (
            f"Action(id='{self.id[:8]}...', tool='{self.tool_id}', "
            f"capability='{self.capability}', status={self.status.value})"
        )
