import uuid
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

from .action import Action
from .goal import GoalContext


class PlanType(str, Enum):
    """The type of plan, indicating its source or purpose."""

    RECIPE = "recipe"
    REMEDIATION = "remediation"


class StepStatus(str, Enum):
    """Execution status of a single step within a plan."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


class PlanStatus(str, Enum):
    """Overall execution status of the entire plan."""

    PENDING = "pending"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"
    PREEMPTED = "preempted"


class PlanStep(BaseModel):
    """
    A single sequence of actions to be executed together.
    """

    id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this specific step (generated on load if missing).",
    )
    description: str = Field(
        description="A natural language explanation of what this step achieves."
    )

    action: Action = Field(description="The atomic command to perform in this step.")

    status: StepStatus = Field(
        default=StepStatus.PENDING, description="The current execution status of this step."
    )
    started_at: datetime | None = Field(
        default=None, description="Timestamp when execution started."
    )
    completed_at: datetime | None = Field(
        default=None, description="Timestamp when execution completed."
    )


class Plan(BaseModel):
    """
    The complete, ordered sequence of steps generated by the planning agent
    to fulfill the user's intent (the Blueprint).
    """

    plan_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for this plan instance.",
    )
    context: GoalContext = Field(description="The original intent and goal this plan addresses.")
    plan_type: PlanType = Field(description="The type of plan (e.g., RECIPE or REMEDIATION).")
    steps: list[PlanStep] = Field(description="The ordered list of steps to execute.")
    status: PlanStatus = Field(
        default=PlanStatus.PENDING, description="The overall execution status of the plan."
    )

    # Optional fields for tracking execution
    created_at: datetime = Field(default_factory=datetime.now)
    started_at: datetime | None = None
    completed_at: datetime | None = None

    def __repr__(self) -> str:
        return (
            f"Plan(id='{self.plan_id[:8]}...', type={self.plan_type.name}, "
            f"status={self.status.name}, steps={len(self.steps)})"
        )
